[package]
name = "sl-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ncurses = "5.101.0"
signal-hook = "0.3.9"
nix = "0.22.0"
crossterm="0.19.0"